"""Expand and normalise the CarePrompt AI tool directory.

Run from the repository root:
    python scripts/update_tool_directory.py

The script is intentionally deterministic so future maintainers can re-run it
after editing the additions or INR guidance below.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DIRECTORY = ROOT / "data" / "tool_directory.csv"
VERIFIED = "2026-07-26"

DEFAULT_COSTS = {
    "Free": "₹0",
    "Freemium": "₹0 free tier; paid plans vary",
    "Open source": "₹0 licence; hosting may cost extra",
    "Paid": "₹ Plan- or quote-based",
}

TOOL_COST_OVERRIDES = {
    "Scite": "≈₹1,930/month; verify current plan",
}

ADDITIONS = [
    {
        "tool": "Hemingway Editor",
        "category": "Academic writing",
        "access": "Free",
        "cost_inr": "₹0 web editor",
        "best_for": "Readability and concise plain-language editing",
        "patient_data": "Do not enter identifiable or confidential text",
        "citation_support": "Not a source verifier",
        "ease": "5",
        "advantages": "Fast readability feedback without specialist training",
        "limitations": "Can oversimplify clinical or scientific nuance",
        "official_url": "https://hemingwayapp.com/",
        "last_verified": VERIFIED,
        "verification_note": "Official product page checked; web editor is free",
    },
    {
        "tool": "TeXstudio",
        "category": "Academic writing",
        "access": "Open source",
        "cost_inr": "₹0 licence",
        "best_for": "Local LaTeX manuscript and reference workflows",
        "patient_data": "Suitable locally with governance",
        "citation_support": "BibTeX and reference checking",
        "ease": "3",
        "advantages": "Local cross-platform writing with no subscription",
        "limitations": "Requires LaTeX knowledge and local setup",
        "official_url": "https://www.texstudio.org/",
        "last_verified": VERIFIED,
        "verification_note": "Official project page confirms open-source availability",
    },
    {
        "tool": "Jenni AI Plus",
        "category": "Academic writing",
        "access": "Paid",
        "cost_inr": "≈₹1,160/month billed annually; ≈₹2,800 monthly",
        "best_for": "AI-assisted academic drafting, citations and document review",
        "patient_data": "Do not upload confidential manuscripts without approval",
        "citation_support": "Citation features available; verify every source",
        "ease": "5",
        "advantages": "Research-focused drafting and review workflow",
        "limitations": "AI output and references still require expert verification",
        "official_url": "https://jenni.ai/pricing",
        "last_verified": VERIFIED,
        "verification_note": "Official USD pricing converted at about ₹96.5 per US dollar and rounded",
    },
    {
        "tool": "OpenCDS",
        "category": "Clinical evidence",
        "access": "Open source",
        "cost_inr": "₹0 licence; implementation costs vary",
        "best_for": "Standards-based clinical decision-support research and development",
        "patient_data": "Local approved implementation only",
        "citation_support": "Rules and evidence must be curated by implementers",
        "ease": "2",
        "advantages": "Apache-licensed standards-based CDS components",
        "limitations": "Not a ready-to-use clinical advice service; requires validation",
        "official_url": "https://www.opencds.org/",
        "last_verified": VERIFIED,
        "verification_note": "Official project page confirms Apache 2 open-source licensing",
    },
    {
        "tool": "UpToDate",
        "category": "Clinical evidence",
        "access": "Paid",
        "cost_inr": "From ≈₹21,100/year for eligible trainees; professional price varies",
        "best_for": "Evidence-based point-of-care clinical decision support",
        "patient_data": "Use only within approved clinical workflows",
        "citation_support": "Expert-authored evidence with linked references",
        "ease": "5",
        "advantages": "Structured clinical evidence and professional review",
        "limitations": "Subscription and regional availability vary",
        "official_url": "https://www.uptodate.com/home",
        "last_verified": VERIFIED,
        "verification_note": "Official trainee starting price converted from USD; verify role and regional eligibility",
    },
    {
        "tool": "IBM SPSS Statistics",
        "category": "Data & statistics",
        "access": "Paid",
        "cost_inr": "₹ Custom academic or commercial quote",
        "best_for": "Point-and-click statistical analysis and predictive modelling",
        "patient_data": "Use only in an approved governed environment",
        "citation_support": "Methods and sources documented manually",
        "ease": "4",
        "advantages": "Broad statistical procedures and institutional support",
        "limitations": "Licence cost and editions vary; analysis still needs statistical expertise",
        "official_url": "https://www.ibm.com/products/spss-statistics",
        "last_verified": VERIFIED,
        "verification_note": "Official page confirms subscription, perpetual, campus and student licence options",
    },
    {
        "tool": "Ollama",
        "category": "General AI",
        "access": "Open source",
        "cost_inr": "₹0 licence; local compute costs apply",
        "best_for": "Running supported language models locally",
        "patient_data": "Local use still requires institutional governance",
        "citation_support": "Model-dependent; generally weak",
        "ease": "3",
        "advantages": "Local model execution and developer control",
        "limitations": "Hardware, model licensing and validation remain user responsibilities",
        "official_url": "https://ollama.com/",
        "last_verified": VERIFIED,
        "verification_note": "Official project and download page checked",
    },
    {
        "tool": "OpenAI API",
        "category": "General AI",
        "access": "Paid",
        "cost_inr": "Usage-based; about ₹242 per 1M Terra input tokens",
        "best_for": "Building governed AI applications and automated workflows",
        "patient_data": "Use only with approved contracts, controls and data handling",
        "citation_support": "Variable; must be engineered and verified",
        "ease": "2",
        "advantages": "Flexible model and tool integration",
        "limitations": "Requires development, monitoring, cost controls and validation",
        "official_url": "https://developers.openai.com/api/docs/pricing",
        "last_verified": VERIFIED,
        "verification_note": "Illustrative INR conversion of official USD token price; actual usage and taxes vary",
    },
    {
        "tool": "Sante DICOM Viewer Free / Pro",
        "category": "Medical imaging",
        "access": "Freemium",
        "cost_inr": "₹0 Free edition; Pro pricing varies",
        "best_for": "Desktop DICOM viewing with optional professional editions",
        "patient_data": "Local approved use only",
        "citation_support": "Not applicable",
        "ease": "4",
        "advantages": "Free entry edition with a professional upgrade path",
        "limitations": "Windows-focused; verify edition limits and medical-device status",
        "official_url": "https://www.santesoft.com/win/sante-dicom-viewer-free/sante-dicom-viewer-free.html",
        "last_verified": VERIFIED,
        "verification_note": "Official product-family page checked; confirm current edition availability",
    },
    {
        "tool": "OsiriX MD",
        "category": "Medical imaging",
        "access": "Paid",
        "cost_inr": "From ≈₹6,750/month",
        "best_for": "Professional DICOM viewing and post-processing on macOS",
        "patient_data": "Use only in approved clinical environments",
        "citation_support": "Not applicable",
        "ease": "4",
        "advantages": "Full-featured certified medical image viewer",
        "limitations": "macOS-only; licence and clinical governance required",
        "official_url": "https://www.osirix-viewer.com/osirix/osirix-md/",
        "last_verified": VERIFIED,
        "verification_note": "Official starting price of US$69.99/month converted at about ₹96.5 and rounded",
    },
    {
        "tool": "Google Meet",
        "category": "Meeting support",
        "access": "Free",
        "cost_inr": "₹0 personal tier",
        "best_for": "Basic video meetings and collaborative discussions",
        "patient_data": "Do not conduct or record confidential encounters without approval",
        "citation_support": "Not applicable",
        "ease": "5",
        "advantages": "Accessible browser-based meetings",
        "limitations": "Recording, duration and administration features vary by plan",
        "official_url": "https://workspace.google.com/products/meet/",
        "last_verified": VERIFIED,
        "verification_note": "Official product page checked; verify Workspace plan limits",
    },
    {
        "tool": "Whisper",
        "category": "Meeting support",
        "access": "Open source",
        "cost_inr": "₹0 licence; local compute costs apply",
        "best_for": "Local speech recognition and transcription experiments",
        "patient_data": "Local use still requires consent and governance",
        "citation_support": "Not applicable",
        "ease": "2",
        "advantages": "Open local transcription workflow",
        "limitations": "Requires technical setup; errors and language bias require review",
        "official_url": "https://github.com/openai/whisper",
        "last_verified": VERIFIED,
        "verification_note": "Official source repository checked",
    },
    {
        "tool": "Dragon Medical One",
        "category": "Meeting support",
        "access": "Paid",
        "cost_inr": "₹ Custom institutional quote",
        "best_for": "Speech-driven clinical documentation",
        "patient_data": "Use only under an approved organisational deployment",
        "citation_support": "Not applicable",
        "ease": "4",
        "advantages": "Healthcare-focused speech recognition and workflow support",
        "limitations": "Procurement, integration and local governance are required",
        "official_url": "https://www.microsoft.com/en-us/health-solutions/clinical-workflow/dragon-medical-one",
        "last_verified": VERIFIED,
        "verification_note": "Official Microsoft healthcare product page checked; pricing is quote-based",
    },
    {
        "tool": "Argos Translate",
        "category": "Patient communication",
        "access": "Open source",
        "cost_inr": "₹0 licence; local compute costs apply",
        "best_for": "Local offline machine-translation experiments",
        "patient_data": "Local use still requires privacy review",
        "citation_support": "Not applicable",
        "ease": "3",
        "advantages": "Offline open-source translation",
        "limitations": "Medical accuracy and language coverage require bilingual review",
        "official_url": "https://www.argosopentech.com/",
        "last_verified": VERIFIED,
        "verification_note": "Official project page checked",
    },
    {
        "tool": "DeepL Pro",
        "category": "Patient communication",
        "access": "Paid",
        "cost_inr": "From ≈₹845/month billed annually",
        "best_for": "Professional translation drafts and document translation",
        "patient_data": "Use only under approved privacy terms and workflow",
        "citation_support": "Not applicable",
        "ease": "5",
        "advantages": "Professional translation features and glossary support",
        "limitations": "Clinical nuance still requires qualified bilingual review",
        "official_url": "https://www.deepl.com/en/pro",
        "last_verified": VERIFIED,
        "verification_note": "Official starting price of US$8.74/month converted at about ₹96.5 and rounded",
    },
    {
        "tool": "Google Slides",
        "category": "Presentation",
        "access": "Free",
        "cost_inr": "₹0 personal tier",
        "best_for": "Collaborative presentations and simple workshop decks",
        "patient_data": "Do not upload patient data or images without approval",
        "citation_support": "Citations added manually",
        "ease": "5",
        "advantages": "Accessible real-time collaboration",
        "limitations": "Advanced governance and organisational controls depend on plan",
        "official_url": "https://workspace.google.com/products/slides/",
        "last_verified": VERIFIED,
        "verification_note": "Official product page checked",
    },
    {
        "tool": "LibreOffice Impress",
        "category": "Presentation",
        "access": "Open source",
        "cost_inr": "₹0 licence",
        "best_for": "Local offline presentation creation",
        "patient_data": "Suitable locally with governance",
        "citation_support": "Citations added manually",
        "ease": "4",
        "advantages": "No subscription and local file control",
        "limitations": "Compatibility and advanced collaboration may be limited",
        "official_url": "https://www.libreoffice.org/discover/impress/",
        "last_verified": VERIFIED,
        "verification_note": "Official open-source office-suite page checked",
    },
    {
        "tool": "Beautiful.ai Pro",
        "category": "Presentation",
        "access": "Paid",
        "cost_inr": "From ≈₹1,160/month billed annually",
        "best_for": "AI-assisted professional slide design",
        "patient_data": "Do not upload confidential or patient content",
        "citation_support": "Citations added and verified manually",
        "ease": "5",
        "advantages": "Guided layouts and consistent visual design",
        "limitations": "Subscription, export and AI accuracy require review",
        "official_url": "https://www.beautiful.ai/pricing",
        "last_verified": VERIFIED,
        "verification_note": "Official Pro price of US$12/month billed annually converted and rounded",
    },
    {
        "tool": "MyBib",
        "category": "Reference management",
        "access": "Free",
        "cost_inr": "₹0",
        "best_for": "Generating and exporting common citation styles",
        "patient_data": "Do not enter patient information",
        "citation_support": "Formats citations; metadata must be verified",
        "ease": "5",
        "advantages": "Free browser-based citation generation",
        "limitations": "Source metadata and style details can still be wrong",
        "official_url": "https://www.mybib.com/",
        "last_verified": VERIFIED,
        "verification_note": "Official product pages describe the citation generator as free",
    },
    {
        "tool": "Paperpile",
        "category": "Reference management",
        "access": "Paid",
        "cost_inr": "From ≈₹400/month for eligible academics, billed annually",
        "best_for": "Cloud reference management and Google Docs or Word citation",
        "patient_data": "Do not store patient information",
        "citation_support": "Reference collection, organisation and citation",
        "ease": "5",
        "advantages": "Integrated browser and document citation workflow",
        "limitations": "Subscription required after trial; metadata still needs checking",
        "official_url": "https://paperpile.com/pricing/",
        "last_verified": VERIFIED,
        "verification_note": "Official academic price of US$4.15/month converted at about ₹96.5 and rounded",
    },
    {
        "tool": "Open Knowledge Maps",
        "category": "Research discovery",
        "access": "Open source",
        "cost_inr": "₹0 hosted access; self-hosting may cost extra",
        "best_for": "Visual exploration of scientific topics and related literature",
        "patient_data": "Do not enter confidential information",
        "citation_support": "Paper-linked discovery; verify original sources",
        "ease": "4",
        "advantages": "Open, nonprofit visual discovery platform",
        "limitations": "Exploratory mapping is not a systematic search",
        "official_url": "https://openknowledgemaps.org/",
        "last_verified": VERIFIED,
        "verification_note": "Official page confirms open-source software and hosted access",
    },
]


def main() -> None:
    with DIRECTORY.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    addition_costs = {item["tool"]: item["cost_inr"] for item in ADDITIONS}
    for row in rows:
        row["cost_inr"] = addition_costs.get(
            row["tool"],
            TOOL_COST_OVERRIDES.get(row["tool"], DEFAULT_COSTS[row["access"]]),
        )

    known_tools = {row["tool"] for row in rows}
    rows.extend(item for item in ADDITIONS if item["tool"] not in known_tools)
    rows.sort(key=lambda item: (item["category"], item["access"], item["tool"].lower()))

    fieldnames = [
        "tool",
        "category",
        "access",
        "cost_inr",
        "best_for",
        "patient_data",
        "citation_support",
        "ease",
        "advantages",
        "limitations",
        "official_url",
        "last_verified",
        "verification_note",
    ]
    with DIRECTORY.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


if __name__ == "__main__":
    main()
